# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1047, 850)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tb_analy_res = QtWidgets.QTextBrowser(self.tab)
        self.tb_analy_res.setGeometry(QtCore.QRect(580, 210, 351, 511))
        self.tb_analy_res.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_analy_res.setObjectName("tb_analy_res")
        self.pb_analy_start = QtWidgets.QPushButton(self.tab)
        self.pb_analy_start.setGeometry(QtCore.QRect(580, 110, 141, 41))
        self.pb_analy_start.setMinimumSize(QtCore.QSize(101, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/play_button_48px_1201205_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_analy_start.setIcon(icon)
        self.pb_analy_start.setIconSize(QtCore.QSize(30, 30))
        self.pb_analy_start.setObjectName("pb_analy_start")
        self.pb_analy_stop = QtWidgets.QPushButton(self.tab)
        self.pb_analy_stop.setGeometry(QtCore.QRect(740, 110, 131, 41))
        self.pb_analy_stop.setMinimumSize(QtCore.QSize(101, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/stop_48px_1229026_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_analy_stop.setIcon(icon1)
        self.pb_analy_stop.setIconSize(QtCore.QSize(30, 30))
        self.pb_analy_stop.setObjectName("pb_analy_stop")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(70, 170, 141, 31))
        self.label_4.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.te_filename = QtWidgets.QTextEdit(self.tab)
        self.te_filename.setGeometry(QtCore.QRect(70, 110, 251, 31))
        self.te_filename.setMinimumSize(QtCore.QSize(201, 0))
        self.te_filename.setObjectName("te_filename")
        self.pb_analy_choose = QtWidgets.QPushButton(self.tab)
        self.pb_analy_choose.setGeometry(QtCore.QRect(340, 110, 161, 31))
        self.pb_analy_choose.setMinimumSize(QtCore.QSize(101, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../red-green-blindness/demo/image/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_analy_choose.setIcon(icon2)
        self.pb_analy_choose.setIconSize(QtCore.QSize(30, 30))
        self.pb_analy_choose.setObjectName("pb_analy_choose")
        self.tb_analy_input = QtWidgets.QTextEdit(self.tab)
        self.tb_analy_input.setGeometry(QtCore.QRect(70, 210, 371, 511))
        self.tb_analy_input.setMinimumSize(QtCore.QSize(201, 0))
        self.tb_analy_input.setObjectName("tb_analy_input")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(70, 30, 731, 51))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(580, 170, 141, 31))
        self.label_5.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/web_code_48px_1179075_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.te_slr_input = QtWidgets.QTextEdit(self.tab_2)
        self.te_slr_input.setObjectName("te_slr_input")
        self.gridLayout.addWidget(self.te_slr_input, 3, 0, 1, 1)
        self.tb_slr = QtWidgets.QTextBrowser(self.tab_2)
        self.tb_slr.setObjectName("tb_slr")
        self.gridLayout.addWidget(self.tb_slr, 5, 1, 1, 2)
        self.tb_quad = QtWidgets.QTextBrowser(self.tab_2)
        self.tb_quad.setObjectName("tb_quad")
        self.gridLayout.addWidget(self.tb_quad, 5, 3, 1, 3)
        self.tb_table = QtWidgets.QTextBrowser(self.tab_2)
        self.tb_table.setObjectName("tb_table")
        self.gridLayout.addWidget(self.tb_table, 5, 0, 1, 1)
        self.tb_vn = QtWidgets.QTextBrowser(self.tab_2)
        self.tb_vn.setObjectName("tb_vn")
        self.gridLayout.addWidget(self.tb_vn, 3, 3, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 4, 1, 1, 1)
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_9.setMinimumSize(QtCore.QSize(500, 0))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.gridLayout.addWidget(self.textBrowser_9, 3, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setMinimumSize(QtCore.QSize(27, 61))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.pb_slr_stop = QtWidgets.QPushButton(self.tab_2)
        self.pb_slr_stop.setIcon(icon1)
        self.pb_slr_stop.setIconSize(QtCore.QSize(30, 30))
        self.pb_slr_stop.setObjectName("pb_slr_stop")
        self.gridLayout.addWidget(self.pb_slr_stop, 1, 4, 1, 1)
        self.pb_slr_quad = QtWidgets.QPushButton(self.tab_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/brand_brands_excel_logo_48px_1212964_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_slr_quad.setIcon(icon4)
        self.pb_slr_quad.setIconSize(QtCore.QSize(30, 30))
        self.pb_slr_quad.setObjectName("pb_slr_quad")
        self.gridLayout.addWidget(self.pb_slr_quad, 1, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 3, 1, 1)
        self.pb_slr_start = QtWidgets.QPushButton(self.tab_2)
        self.pb_slr_start.setIcon(icon)
        self.pb_slr_start.setIconSize(QtCore.QSize(30, 30))
        self.pb_slr_start.setObjectName("pb_slr_start")
        self.gridLayout.addWidget(self.pb_slr_start, 1, 3, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/gear_48px_1180534_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/binary_code_48px_1219813_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../chrmoedownload/about_help_smart_watch_35.185520361991px_1225400_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon7, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "小型编译器"))
        self.pb_analy_start.setText(_translate("mainWindow", "开始"))
        self.pb_analy_stop.setText(_translate("mainWindow", "停止"))
        self.label_4.setText(_translate("mainWindow", "载入源程序符号串"))
        self.pb_analy_choose.setText(_translate("mainWindow", "选择源文件"))
        self.label.setText(_translate("mainWindow", "提示：该页面用于词法分析，选择.c源程序，将会输出词法分析后的二元组。并储存在tokens.txt中"))
        self.label_5.setText(_translate("mainWindow", "词法分析结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "词法分析"))
        self.te_slr_input.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\">//</span><span style=\" font-family:\'新宋体\'; font-size:12pt;\">我是注释</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt;\"><br />void main(){<br />    int a ;<br />    a=2*(2+3)-3;<br />    if (a&lt;3){<br />        a=100;<br />    }<br />    return;<br />}</span></p></body></html>"))
        self.label_22.setText(_translate("mainWindow", "slr分析表"))
        self.label_25.setText(_translate("mainWindow", "分析过程"))
        self.textBrowser_9.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">G[S]:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">S-&gt;km(){Pr}</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">P-&gt;KAI|KA</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">I-&gt;i(C){A}</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">C-&gt;v&lt;d|v&gt;d</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">K-&gt;kv</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">A-&gt;v=E</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">E-&gt;E+T|E-T|T</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">T-&gt;T*F|T/F|F</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">F-&gt;(E)|d</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:10.5pt;\">V-&gt;d</span></p></body></html>"))
        self.label_24.setText(_translate("mainWindow", "vn、vt、first、follow集合"))
        self.label_2.setText(_translate("mainWindow", "提示：该页面用于语法制导翻译，读入词法分析结果的token.txt，并展示first集合，follow集，slr表，和最终的四元组信息"))
        self.pb_slr_stop.setText(_translate("mainWindow", "停止"))
        self.pb_slr_quad.setText(_translate("mainWindow", "生成四元组"))
        self.label_27.setText(_translate("mainWindow", "输入源程序字符串"))
        self.label_26.setText(_translate("mainWindow", "SLR(1)文法"))
        self.label_21.setText(_translate("mainWindow", "四元组结果"))
        self.pb_slr_start.setText(_translate("mainWindow", "开始分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "语法制导"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "生成汇编代码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "关于我"))

